### PR TITLE
pt_rBR Translation

### PR DESCRIPTION
**Pull request by gabrielfvale**
Brazillian portuguese translation for Pokémesh

### CODE REVIEW

**Comment by iGio90** [comment]
ready to merge? :) make another commit and add credits to you for the translation!

**Comment by iGio90** [comment]
`<string name="portuguese_translations_credits" translatable="false">gabrielfvale</string>`

**Comment by gabrielfvale** [comment]
All done! :D

**Comment by iGio90** [comment]
merged! thank you :)

**Pull request merged**
